spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:h2:tcp://localhost/~/hotel_gabriella;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jwt:
    expire:
      accessTokenValidMilliSeconds: 60000  #60 x 10 x 1000 : 1분
      refreshTokenValidMilliSeconds: 604800000 #60 x 60 x 24 x 7 x 1000 : 1주

  redis:
    host: localhost #기본 값
    port: 6379  #기본 값

